esphome:
  name: esp_name
  friendly_name: esp_friendly_name

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: Esp Fallback Hotspot
    password: !secret ap_password

captive_portal:

  
external_components:  
  - source: github://pr#13133
    components: [ds1603l]
    refresh: 0d
 
uart: 
  - id: tank1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600 

  - id: tank2
    tx_pin: GPIO1    
    rx_pin: GPIO3 
    baud_rate: 9600    

sensor:
##############
### Tank 1 ###
##############
  - platform: ds1603l 
    uart_id: tank1
    ds1603l_min_level: 0.0
    ds1603l_max_level: 600.0
    ds1603l_min_volume: 0.0
    ds1603l_max_volume: 55.0
    ds1603l_liquid_level:
      device_class: distance 
      name: "Gray Distance"
      unit_of_measurement: "mm"
      icon: mdi:arrow-expand-vertical
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 0.1
    ds1603l_liquid_volume:
      name: "Gray Volume"
      unit_of_measurement: "gal"
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 1.0
    ds1603l_percentage:
      name: "Gray Percent"
      filters:
        - filter_out: 0
        - filter_out: nan

##############
### Tank 2 ###
##############
  - platform: ds1603l
    uart_id: tank2
    ds1603l_min_level: 20.0
    ds1603l_max_level: 600.0
    ds1603l_min_volume: 0.0
    ds1603l_max_volume: 55.0
    ds1603l_liquid_level:
      name: "Black Distance"
      device_class: distance 
      unit_of_measurement: "mm"
      icon: mdi:arrow-expand-vertical 
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 0.1
    ds1603l_liquid_volume:
      name: "Black Volume"
      unit_of_measurement: "gal"
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 1.0
    ds1603l_percentage:
      name: "Black Percent"
      filters:
        - filter_out: 0
        - filter_out: nan
