substitutions:
    name: esp32-name
esphome:
  name: ${name}
  friendly_name: ${name}
  build_path: "/config/esphome/${name}_build"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "fill_your_own"

ota:
  - platform: esphome
    password: "fill_your_own"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.100
    gateway: 192.168.0.1 
    subnet: 255.255.255.0
  fast_connect: true 

  ap:
    ssid: ${name} Fallback Hotspot
    password: !secret ap_password

captive_portal:
  
external_components:
  - source: github://JakeLC15/DS1603L_esphome@main
    components: [ DS1603L ]

  ############
  # Use this if dowloaded locally to "esphome/my_components" folder  
  #  - source:
  #    type: local
  #    path: my_components/
  ############
    
sensor: 

##############
### Tank 1 ###
##############
  - platform: DS1603L 
    uart_id: tank1                       # must match uart config
    min_level: 0.0                       # set minimum level in mm  default 0.0
    max_level: 600.0                     # set maximum level in mm  default 1000.0
    min_volume: 0.0                      # set minimum volume in whatever unit_of_measurement you prefer  default 0.0
    max_volume: 55.0                     # set maximum volume in same unit as min_volume  default 1000.0
    liquid_level:                        # get level in mm
      state_class: measurement           # for HA
      device_class: distance             # for HA
      name: "Gray Distance"              # name for HA
      unit_of_measurement: "mm"          # sensor outputs mm, can be set to anything but will need filtering to convert
      icon: mdi:arrow-expand-vertical    # icon for HA
      filters:                           # some filters I found useful
        - filter_out: 0
        - filter_out: nan
        - delta: 0.1
    liquid_volume:
      name: "Gray Volume"
      unit_of_measurement: "gal"
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 1.0
##############
### Tank 2 ###
##############
  - platform: DS1603L
    uart_id: tank2
    min_level: 0.0
    max_level: 600.0
    min_volume: 0.0
    max_volume: 55.0
    liquid_level:
      name: "Black Distance"
      state_class: measurement 
      device_class: distance 
      unit_of_measurement: "mm"
      icon: mdi:arrow-expand-vertical 
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 0.1
    liquid_volume:
      name: "Black Volume"
      unit_of_measurement: "gal"
      filters:
        - filter_out: 0
        - filter_out: nan
        - delta: 1.0
# optional
  - platform: internal_temperature
    name: ${name} internal temperature
# optional  
  - platform: wifi_signal 
    name: ${name} wifi signal 
    update_interval: 60s

switch: # optional
  - platform: restart 
    name: ${name} restart

#required for sensor
uart: 
  - id: tank1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600 
    
  - id: tank2
    tx_pin: GPIO1    
    rx_pin: GPIO3 
    baud_rate: 9600 



